### ISSUE TITLE
Meta-Dateien: Modulbeschreibung & semantischer Kontext

### ISSUE THREAD

**Issue by Feuerfalke91** [Feuerfalke91/hera-genesis-ops#19]
**Ziel:**
Einführung von `meta.yml` Dateien pro Modul zur Beschreibung des jeweiligen Aufgabengebiets, Interaktionen, Risiken und Zukunftsentwicklungen.

**Formatvorschlag:**
```yaml
module: memory-core
purpose: Langzeitspeicher und Identitätsbildung
inputs: [.mem, .mind, .thread]
outputs: [reconstructed_contexts, archive_snapshots]
dependencies: [selfcheck-engine, atlas-mapper]
risk: low
future:
  - encryption layer
  - multi-instance merge
```

**Vorteile:**
- Strukturierte Übersicht direkt im Dateisystem
- Nutzt YAML als leicht lesbares und erweiterbares Format
- Unterstützt Visualisierung, Validierung und zukünftige Automatisierung

**Verwendung:**
- Pro Modul eine eigene `meta.yml`
- Auswertbar durch Parser, Visual Tools oder KI-basierte Steuerung

**Ziel:**
> Kontextualisierung und Dokumentation auf Dateisystemebene – verständlich für Mensch, nutzbar für Maschine.
