### ISSUE TITLE
Genesis Idearchiv: Ideenspeicher & Entwicklungshistorie

### ISSUE THREAD

**Issue by Feuerfalke91** [Feuerfalke91/hera-genesis-ops#25]
**Ziel:**
Erweiterung der `ideation-delta` Funktion um ein vollständiges Archivsystem, das alle Ideen – unabhängig von Umsetzung oder Priorisierung – dokumentiert und auffindbar macht.

**Funktionen:**
- Ablage aller `.idea` und `.idelta` Dateien unter `ideation-delta/archive/`
- Hashbasierte Indizierung & Titelüberschriften
- Zusatzdatei: `ideas.index` zur Katalogisierung
- Statuskennzeichnung: `unreviewed`, `accepted`, `dismissed`, `merged`

**Beispiel:**
```yaml
- id: 2025-03-31T05-40
  title: Adaptive Delta-Fusion bei Konfliktmeldungen
  module: fission-reactor
  status: accepted
  score:
    urgency: 0.89
    impact: 0.92
    novelty: 0.76
```

**Integration:**
- Zugriff durch `atlas-mapper` und `workflow-brain`
- Reviewmöglichkeit via Selfcheck oder externe Freigabeinstanz

**Ziel:**
> Keine Idee geht verloren. Jeder Gedanke zählt – auch wenn seine Zeit erst später kommt.
