### ISSUE TITLE
Genesis Control-Flow: Steuerungsmodul für Statusflags & Aktivierungskaskaden

### ISSUE THREAD

**Issue by Feuerfalke91** [Feuerfalke91/hera-genesis-ops#27]
**Ziel:**
Implementierung eines zentralen Kontrollsystems zur Verwaltung von Aktivierungs- und Deaktivierungslogiken, Statusübergängen und Prozessabhängigkeiten.

**Funktionen:**
- Analyse und Reaktion auf Flags (`.flag`) und Zustandsdateien
- Aktivierung oder Pausierung von Modulen durch `workflow-brain`
- Erzeugung von Triggerketten durch `.chain` Dateien (modulübergreifende Ereignisketten)
- Verwaltung von Systemzuständen in `state.core.yml`

**Beispiel `state.core.yml`:**
```yaml
modules:
  memory-core: active
  selfcheck-engine: active
  ideation-delta: paused
  interface-vault: error
```

**Trigger-Ketten:**
- `core.chain`: "Wenn delta.error → stop(fission-reactor) → trigger(snapshot) → notify(operator)"

**Integration:**
- Zentral über `workflow-brain` ansprechbar
- Direkt verlinkt mit `selfcheck-engine`, `atlas-mapper`, `log-core`

**Ziel:**
> Genesis steuert sich wie ein lebendiger Organismus – gezielt, modular, dynamisch. Kein Modul bleibt unkoordiniert.
